(in-package :titechfes)

(define-class gamecharacter (gameobject)
  (hp 100)
  (dx 0)
  (dy 0)
  (ax 0)
  (ay 0)
  (rvx 0)
  (rvy 0)
  (muteki nil)
  (muteki-count 0)
  (muteki-time 10))

(defmethod alive-detect ((char gamecharacter))
  (when (<= (hp char) 0)
    (kill char)))

(defmethod dec-muteki-frame ((chr gamecharacter))
  (if (and (muteki chr) (zerop  (muteki-count chr)))
      (setf (muteki chr) nil)
      (decf (muteki-count chr))))

(defmethod update-object ((chr gamecharacter) game)
  (dec-muteki-frame chr)
  (alive-detect chr)
  (incf (get-x chr) (dx chr))
  (incf (get-y chr) (dy chr))
  (when (out-of-map-p chr game)
    (kill chr)))

(defmethod attack ((obj gameobject) (char gamecharacter))
  (when (not (muteki char))
    (decf (hp char) (atk obj))
    (setf (muteki char) t
	  (muteki-count char) (muteki-time char)
	  (ax char) (pmif (plusp (- (get-x char) (get-x obj)))
			  (knock-back-atk obj))
	  (ay char) -10)))

