(in-package titechfes)

(define-class game ()
  (window-size '(640 480))
  (map-size nil)
  (camera '(0 0))
  (player nil)
  (all-object nil)
  (mapchips nil)
  (enemies nil)
  (enemy-bullets nil)
  (bullets nil)
  (keystate (make-instance 'titechfes-key)))
