(in-package :titechfes)

(defparameter *game* nil)

(defun mapchip-image-load ()
  (load-images '(:wall "wall_g.png")
	       '(:dameged-wall "damaged_wall_g.png")
	       '(:dameged2-wall "damaged2_wall_g.png")))

(defun chara-image-load ()
  (load-images '(:player-l "me2.png")
	       '(:player-r "me.png")
	       '(:enemy-l "enemy2.png")
	       '(:enemy-r "enemy.png")
	       '(:demon-gate "demon-gate.png")
	       '(:enemy2-l "minienemy2.png")
	       '(:enemy2-r "minienemy1.png")
	       '(:big "big.png")
	       '(:big-l "big-l.png")))

(defun bullet-image-load ()
  (load-images '(:knife-l "knife2-l.png")
	       '(:knife-r "knife2-r.png")
	       '(:javelin-l "javelin-l.png")
	       '(:javelin-r "javelin-r.png")
	       '(:explosion "explosion.png")
	       '(:ebul "ebul.png"))
  (load-animations '(:boomerang-l "boomerang-l_ani.png"
		     24 24 96 24)
		   '(:boomerang-r "boomerang-r_ani.png"
		     24 24 96 24)
		   '(:axe-l "axe-l_ani.png"
		     24 24 96 24)
		   '(:axe-r "axe-r_ani.png"
		     24 24 96 24)
		   '(:bomb-l "bomb-l_ani.png"
		     24 24 96 24)
		   '(:bomb-r "bomb-r_ani.png"
		     24 24 96 24)))

(defun item-image-load ()
  (load-images '(:coin "coin.png")
	       '(:dash-up "dash_up.png")
	       '(:jump-up "jump_up.png")
	       '(:goal "goal.png")
	       '(:knife-item "knife_item.png")
	       '(:axe-item "axe_item.png")
	       '(:boomerang-item "boomerang_item.png")
	       '(:javelin-item "javelin_item.png")
	       '(:bomb-item "bomb_item.png")))

(defun icon-image-load ()
  (load-images       '(:knife-icon "knife_icon.png")
		     '(:axe-icon "axe_icon.png")
		     '(:boomerang-icon "boomerang_icon.png")
		     '(:javelin-icon "javelin_icon.png")
		     '(:bomb-icon "bomb_icon.png")))

(defun gameimage-load ()
  (mapchip-image-load)
  (chara-image-load)
  (bullet-image-load)
  (item-image-load)
  (icon-image-load)
  (load-images '(:title "title_touka.png")))

;------------------main------------------
(defun run ()
  (sdl:with-init ()
    (sdl:window 640 480 :title-caption "魔津村")
    (sdl:initialise-default-font  sdl:*font-9x18b*)
    (gameimage-load)
    (return-boomerang)
    (setf (sdl:frame-rate) 60)
    (let ((game (make-instance 'game)))
      (init-camera game)
      (sdl:update-display)
      (setf *game* game)
      (sdl:with-events ()
	(:quit-event () t)
	(:video-expose-event () (sdl:update-display))
	(:key-down-event (:key key)
			 (if (sdl:key= key :sdl-key-escape)
			     (sdl:push-quit-event)
			     (update-key-state key 3
				(keystate game))))
	(:key-up-event (:key key)
		       (update-key-state key 2
			   (keystate game)))
	(:idle (run-state game)
	       (sdl:update-display)
	       (next-key-state (keystate game)))))))
